In [1]:
import pandas as pd

df = pd.read_csv('winequality.csv', index_col=0)

df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,wine_is_red
0,5.9,0.61,0.08,2.1,0.071,16.0,24.0,0.99376,3.56,0.77,11.1,6,1
1,8.2,1.00,0.09,2.3,0.065,7.0,37.0,0.99685,3.32,0.55,9.0,6,1
2,6.4,0.24,0.49,5.8,0.053,25.0,120.0,0.99420,3.01,0.98,10.5,6,0
3,6.6,0.23,0.26,1.3,0.045,16.0,128.0,0.99340,3.36,0.60,10.0,6,0
4,7.2,0.24,0.29,3.0,0.036,17.0,117.0,0.99411,3.36,0.68,10.1,6,0

In [2]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,wine_is_red
count,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000
mean,7.215307,0.339666,0.318633,5.443235,0.056034,30.525319,115.744574,0.994697,3.218501,0.531268,10.491801,5.818378,0.246114
std,1.296434,0.164636,0.145318,4.757804,0.035034,17.749400,56.521855,0.002999,0.160787,0.148806,1.192712,0.873255,0.430779
min,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.720000,0.220000,8.000000,3.000000,0.000000
25%,6.400000,0.230000,0.250000,1.800000,0.038000,17.000000,77.000000,0.992340,3.110000,0.430000,9.500000,5.000000,0.000000
50%,7.000000,0.290000,0.310000,3.000000,0.047000,29.000000,118.000000,0.994890,3.210000,0.510000,10.300000,6.000000,0.000000
75%,7.700000,0.400000,0.390000,8.100000,0.065000,41.000000,156.000000,0.996990,3.320000,0.600000,11.300000,6.000000,0.000000
max,15.900000,1.580000,1.660000,65.800000,0.611000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000,9.000000,1.000000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         6497 non-null   float64
 1   volatile acidity      6497 non-null   float64
 2   citric acid           6497 non-null   float64
 3   residual sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free sulfur dioxide   6497 non-null   float64
 6   total sulfur dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64
 12  wine_is_red           6497 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 710.6 KB

Nulos e NaNs

In [4]:
print("Nulos: ", (df.isnull().sum()), sep='\n')
print("NaNs: ", (df.isna().sum()), sep='\n')

Nulos:
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
wine_is_red             0
dtype: int64
NaNs:
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
wine_is_red             0
dtype: int64

Valores Únicos

In [5]:
print(df['wine_is_red'].unique())
print(df['quality'].unique())

[1 0]
[6 7 5 4 8 3 9]

In [18]:
from collections import Counter
import numpy as np

class KNN():
    def __init__(self, k):
        self.k = k
    
    def fit(self, X, y):
        self.X = X
        self.y = y

    def _distance(self, x1, x2):
        return np.sqrt(np.sum((x1 - x2) ** 2))

    def _predict_one(self, x):
        print('Entrei na função predict_one')
        distances = []
        for j in range(self.X.shape[0]):
            print(f'Entrei no for (predict_one) pela {j}ª vez')
            distances.append((j, self._distance(x, self.X[j])))
        print('Sai do for (predict_one)')
        distances.sort(key=lambda x: x[1])
        top_k = [self.y[i] for i, _ in distances[:self.k]]
        return Counter(top_k).most_common(1)[0][0]

    def predict(self, X):
        y_pred = []
        print('Entrei na função predict')
        for i in range(X.shape[0]):
            print(f'Entrei no for (predict) pela {i}ª vez')
            y_pred.append(self._predict_one(X[i]))
        print('Sai da função predict')
        return np.array(y_pred)

### Treinando sem normalizar os dados

Separando as labels do dataset

In [9]:
class_is_red = df.wine_is_red
class_quality = df.quality
X = df.drop('wine_is_red', axis=1)
X = X.drop('quality', axis=1)
print(X.shape, class_is_red.shape, class_quality.shape, sep='\n')

(6497, 11)
(6497,)
(6497,)

In [19]:
model = KNN(k = 3)
model.fit(X, class_is_red)
pred = model.predict(X)

Entrei na função predict
Entrei no for (predict) pela 0ª vez

KeyError: 0